#!/bin/bash

# To use, simply type ./copyfromakka username remote_file_path local_file_path

baseremotedir=$1"@akka.d.umn.edu:/home/csugrads/"$1"/cs1521"
remotefile=$2
localfile=$3

scp $baseremotedir$remotefile $localfile
