#!/bin/bash

temp=$1

if temp=="help"; then
	echo "Output's the four rules for success, with a 1 second seperation between lines."
	exit
fi

echo "The Four Rules:"
sleep 1
echo "No More Zero Days!"
sleep 1
echo "Thank Your 3 Selves!"
sleep 1
echo "Forgive Yourself!"
sleep 1
echo "Exersize and Books!"
sleep 1

